// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDY59VoADMZ-gIdPELuEfssyz30aa6DDY',
    appId: '1:414276596017:web:7595eca7592bc385b08010',
    messagingSenderId: '414276596017',
    projectId: 'fir-ci-2a548',
    authDomain: 'fir-ci-2a548.firebaseapp.com',
    storageBucket: 'fir-ci-2a548.firebasestorage.app',
    measurementId: 'G-N0CB6XHE1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8NnJQ2IzBS0s3XXOE0wVBpIboI5T8MGM',
    appId: '1:414276596017:android:62b6ded9a095b96ab08010',
    messagingSenderId: '414276596017',
    projectId: 'fir-ci-2a548',
    storageBucket: 'fir-ci-2a548.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC28F70myFx3LVbzjqHj-_XQvn-X-zOzj4',
    appId: '1:414276596017:ios:b286cf7128433201b08010',
    messagingSenderId: '414276596017',
    projectId: 'fir-ci-2a548',
    storageBucket: 'fir-ci-2a548.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCicd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC28F70myFx3LVbzjqHj-_XQvn-X-zOzj4',
    appId: '1:414276596017:ios:b286cf7128433201b08010',
    messagingSenderId: '414276596017',
    projectId: 'fir-ci-2a548',
    storageBucket: 'fir-ci-2a548.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCicd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDY59VoADMZ-gIdPELuEfssyz30aa6DDY',
    appId: '1:414276596017:web:c38eeddb87bbf02cb08010',
    messagingSenderId: '414276596017',
    projectId: 'fir-ci-2a548',
    authDomain: 'fir-ci-2a548.firebaseapp.com',
    storageBucket: 'fir-ci-2a548.firebasestorage.app',
    measurementId: 'G-H4KRVKVE8V',
  );
}
